spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/patient_support_db
spring.datasource.username=sudeepvanga

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
